export const types = {
  LOADING_USER: "LOADING_USER",
  ERROR_USER: "ERROR_USER",
  SET_FOLLOW_USER: "SET_FOLLOW_USER",
  SET_UNFOLLOW_USER: "SET_UNFOLLOW_USER",
  SET_APPROVE_USER: "SET_APPROVE_USER",
  SET_EDIT_USER: "SET_EDIT_USER",
  RESET_USER_LOG: "RESET_USER_LOG",
};
